# Generated by Django 3.1.3 on 2020-11-26 15:12

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Admin', '0003_roledetail'),
    ]

    operations = [
        migrations.CreateModel(
            name='CareerCategory',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category_id', models.IntegerField(default=0)),
                ('category', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='SubCategory',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sub_category', models.CharField(max_length=255)),
                ('create_date', models.DateTimeField(default=datetime.datetime.now)),
                ('cat_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Admin.careercategory')),
            ],
        ),
        migrations.CreateModel(
            name='CategoryCourse',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cfp', models.CharField(max_length=200)),
                ('cat_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Admin.careercategory')),
                ('sub_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Admin.subcategory')),
            ],
        ),
    ]
