# Generated by Django 3.1.3 on 2020-12-01 14:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Admin', '0004_careercategory_categorycourse_subcategory'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userdetails',
            name='user_cfp',
            field=models.BooleanField(blank=True, default=False),
        ),
    ]
