# Generated by Django 3.1.6 on 2021-03-15 08:18

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='BlogCategory',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('blog_category_id', models.IntegerField(default=0)),
                ('blog_category', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='BlogManager',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('blog_title', models.CharField(max_length=100)),
                ('blog_tagline', models.CharField(blank=True, max_length=150)),
                ('blog_body', models.TextField(blank=True)),
                ('blog_thumbnail', models.ImageField(blank=True, null=True, upload_to='blog_images/')),
                ('blog_category', models.CharField(blank=True, max_length=200, null=True)),
                ('blog_date', models.DateTimeField(blank=True, default=datetime.datetime.now)),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='BlogHeight',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('blog_title', models.CharField(max_length=100)),
                ('blog_body', models.TextField(blank=True)),
                ('blog_thumbnail', models.ImageField(blank=True, null=True, upload_to='blog_highlight/')),
                ('blog_date', models.DateTimeField(blank=True, default=datetime.datetime.now)),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
