# Generated by Django 3.1.4 on 2020-12-13 09:05

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('CSM', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='createcourse',
            name='create_id',
        ),
        migrations.AddField(
            model_name='createcourse',
            name='create_user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
