# Generated by Django 3.1.4 on 2020-12-13 10:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('CSM', '0002_auto_20201213_0905'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='createcourse',
            name='create_instructor',
        ),
    ]
