# Generated by Django 3.1.4 on 2021-04-18 05:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('CSM', '0002_week_week_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='week',
            name='week_status',
            field=models.CharField(default='PENDING', max_length=100),
        ),
    ]
