# Generated by Django 3.2.5 on 2021-07-09 17:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('CSM', '0003_auto_20210418_0519'),
    ]

    operations = [
        migrations.CreateModel(
            name='Online_Unit',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('course_title', models.CharField(max_length=500, null=True)),
                ('course_desc', models.CharField(blank=True, max_length=100, null=True)),
                ('date', models.CharField(blank=True, max_length=150, null=True)),
                ('online_class_link', models.CharField(blank=True, max_length=150, null=True)),
                ('test_link', models.CharField(blank=True, max_length=150, null=True)),
                ('extra_link', models.CharField(blank=True, max_length=150, null=True)),
                ('unit_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='CSM.week')),
            ],
        ),
    ]
