# Generated by Django 3.1.4 on 2020-12-17 14:59

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('CSM', '0004_auto_20201213_1313'),
    ]

    operations = [
        migrations.CreateModel(
            name='Week',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('week_private', models.CharField(max_length=100, null=True)),
                ('week_name', models.CharField(max_length=100)),
                ('week_date', models.DateTimeField(blank=True, default=datetime.datetime.now)),
                ('week_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='CSM.course')),
            ],
        ),
        migrations.CreateModel(
            name='Week_Unit',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('unit_caption', models.CharField(max_length=500)),
                ('unit_video1', models.FileField(null=True, upload_to='Week_Videos/')),
                ('unit_video2', models.FileField(null=True, upload_to='Week_Videos/')),
                ('unit_video3', models.FileField(null=True, upload_to='Week_Videos/')),
                ('unit_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='CSM.week')),
            ],
        ),
    ]
