# Generated by Django 3.1.4 on 2020-12-19 05:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('CSM', '0005_week_week_unit'),
    ]

    operations = [
        migrations.AddField(
            model_name='week',
            name='hello',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
