# Generated by Django 3.1.4 on 2020-12-19 05:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('CSM', '0008_remove_week_unit_unit_caption'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Week_Unit',
        ),
    ]
