# Generated by Django 3.1.4 on 2020-12-19 05:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('CSM', '0009_delete_week_unit'),
    ]

    operations = [
        migrations.CreateModel(
            name='Week_Unit',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('unit_video1', models.FileField(null=True, upload_to='Week_Videos/')),
                ('unit_video2', models.FileField(null=True, upload_to='Week_Videos/')),
                ('unit_video3', models.FileField(null=True, upload_to='Week_Videos/')),
                ('unit_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='CSM.week')),
            ],
        ),
    ]
