# Generated by Django 3.1.4 on 2020-12-19 05:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('CSM', '0011_remove_week_unit_unit_video1'),
    ]

    operations = [
        migrations.AddField(
            model_name='week_unit',
            name='unit_video1',
            field=models.FileField(null=True, upload_to='Week_Videos/'),
        ),
    ]
