# Generated by Django 3.1.4 on 2020-12-19 05:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('CSM', '0012_week_unit_unit_video1'),
    ]

    operations = [
        migrations.AddField(
            model_name='week_unit',
            name='unit_caption',
            field=models.CharField(max_length=500, null=True),
        ),
    ]
