# Generated by Django 3.1.4 on 2020-12-19 05:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('CSM', '0014_week_unit_abc'),
    ]

    operations = [
        migrations.AddField(
            model_name='week_unit',
            name='u_capOne',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
