# Generated by Django 3.1.4 on 2020-12-19 05:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('CSM', '0015_week_unit_u_capone'),
    ]

    operations = [
        migrations.RenameField(
            model_name='week_unit',
            old_name='abc',
            new_name='u_capThree',
        ),
        migrations.RemoveField(
            model_name='week_unit',
            name='u_capOne',
        ),
    ]
