# Generated by Django 3.1.4 on 2020-12-19 06:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('CSM', '0018_week_unit_ucap3'),
    ]

    operations = [
        migrations.RenameField(
            model_name='week_unit',
            old_name='uCap3',
            new_name='uCap2',
        ),
    ]
