# Generated by Django 3.1.4 on 2020-12-19 16:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('CSM', '0020_quizz'),
    ]

    operations = [
        migrations.AlterField(
            model_name='quizz',
            name='course_id',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='CSM.course'),
        ),
    ]
