# Generated by Django 3.1.4 on 2021-01-02 05:48

from django.db import migrations
import jsonfield.fields


class Migration(migrations.Migration):

    dependencies = [
        ('CSM', '0021_auto_20201219_1639'),
    ]

    operations = [
        migrations.AddField(
            model_name='quizz',
            name='option',
            field=jsonfield.fields.JSONField(null=True),
        ),
    ]
