# Generated by Django 3.1.4 on 2021-01-02 16:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('CSM', '0022_quizz_option'),
    ]

    operations = [
        migrations.AddField(
            model_name='quizz',
            name='option_available',
            field=models.BooleanField(default=False, null=True),
        ),
    ]
