# Generated by Django 3.1.6 on 2021-02-01 16:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('CSM', '0024_result'),
    ]

    operations = [
        migrations.AddField(
            model_name='week_unit',
            name='video1_duration',
            field=models.TimeField(null=True),
        ),
        migrations.AddField(
            model_name='week_unit',
            name='video2_duration',
            field=models.TimeField(null=True),
        ),
        migrations.AddField(
            model_name='week_unit',
            name='video3_duration',
            field=models.TimeField(null=True),
        ),
    ]
