# Generated by Django 3.1.5 on 2021-02-01 18:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('CSM', '0024_result'),
    ]

    operations = [
        migrations.AlterField(
            model_name='course',
            name='certificate',
            field=models.FileField(null=True, upload_to='csm_certificates/'),
        ),
    ]
