# Generated by Django 3.1.6 on 2021-02-02 14:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('CSM', '0025_auto_20210202_0014'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='xp_points',
            field=models.IntegerField(default=0),
        ),
    ]
