# Generated by Django 3.1.6 on 2021-02-02 06:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('CSM', '0025_auto_20210201_2133'),
    ]

    operations = [
        migrations.AlterField(
            model_name='week_unit',
            name='uCap2',
            field=models.CharField(blank=True, max_length=150, null=True),
        ),
        migrations.AlterField(
            model_name='week_unit',
            name='uCapOne',
            field=models.CharField(blank=True, max_length=150, null=True),
        ),
        migrations.AlterField(
            model_name='week_unit',
            name='u_capThree',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
