# Generated by Django 3.1.6 on 2021-02-02 14:28

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('CSM', '0026_auto_20210202_1218'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='modified',
            field=models.DateTimeField(default=datetime.datetime.now, null=True),
        ),
    ]
