# Generated by Django 3.1.6 on 2021-02-03 07:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('CSM', '0027_course_modified'),
        ('CSM', '0025_auto_20210202_0014'),
    ]

    operations = [
    ]
