# Generated by Django 3.1.6 on 2021-02-03 07:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('CSM', '0028_merge_20210203_1315'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='xp_points_perq',
            field=models.IntegerField(default=0),
        ),
    ]
