# Generated by Django 3.1.6 on 2021-02-04 05:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('CSM', '0026_course_xp_points'),
        ('CSM', '0029_course_xp_points_perq'),
    ]

    operations = [
    ]
