# Generated by Django 3.1.3 on 2020-12-01 15:16

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('Admin', '0005_auto_20201201_1439'),
    ]

    operations = [
        migrations.CreateModel(
            name='CareerChoice',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cat_id', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='Admin.careercategory')),
                ('cfp_id', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='Admin.categorycourse')),
                ('sub_id', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='Admin.subcategory')),
                ('user_id', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
